### ISSUE TITLE
yarn.lock immutability broken by bin

### ISSUE THREAD

**Issue by devthejo** [rohit-gohri/yarn-lock-to-package-json#1]
Hello,

first, thank you for this great tool !

when a `package.json` is containing a `bin` section, the generated `package.json` try to change the `yarn.lock` on `yarn install`

**Comment by rohit-gohri** [comment]
Can you share a small example package.json? So that I can also add a test case

**Comment by rohit-gohri** [comment]
Also, which version of yarn are you using?

**Comment by devthejo** [comment]
{
  "dependencies": {
    "tiged": "^2.12.4"
  },
  "bin": "./bin/my-executable",
}

yarn 3.5.0

**Comment by devthejo** [comment]
here is the PR: https://github.com/rohit-gohri/yarn-lock-to-package-json/pull/3
